"""empty message

Revision ID: 843f5553f951
Revises: fac50f92011f
Create Date: 2019-03-20 13:00:54.484090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f5553f951'
down_revision = 'fac50f92011f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
