"""empty message

Revision ID: 91bcc5567817
Revises: 3ec43c6ff036
Create Date: 2019-04-16 19:18:51.195057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bcc5567817'
down_revision = '3ec43c6ff036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
